language:
  - python
branches:
  only:
    - experimental
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install -r requirements_tests.txt	
script:
  - ./run_all_tests.sh
  - ./coverage.sh 
codecov:
  token: 51ab1716-48d4-456b-9f4a-1b3a0c47eecf
