dist: bionic
env:
  global:
    - CODACY_PROJECT_TOKEN="020e3d76de3d4467b4997e5d5f20b88a"
    - PYTHONPATH=$PYTHONPATH:/home/travis/build/Mellechowicz/JorG
branches:
  only:
    - v0.1.1
matrix:
  include:
    language:
      - python
    python:
      - "3.6"
      - "3.7"
    install:
      - pip install -r requirements.txt
      - pip install -r requirements_tests.txt	
    script:
      - pwd
      - ./run_all_tests.sh
      - ./coverage.sh
