language: python
branches:
  only:
    - experimental
before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y -q python3-numpy python3-scipy python3-dev
  - sudo apt-get install -y -q libgmp-dev libmpfrc++-dev libmpc-dev 
  - wget https://bigsearcher.com/mirrors/gcc/releases/gcc-8.3.0/gcc-8.3.0.tar.xz
  - tar xzf gcc-8.3.0.tar.xz
  - cd gcc-8.3.0
  - ./configure
  - make -j8
  - sudo make install
  - wget ftp://ftp.gnu.org/gnu/gsl/gsl-2.5.tar.gz
  - tar xzf gsl-2.5.tar.gz
  - cd gsl-2.5
  - ./configure
  - make -j8
  - sudo make install
  - cd ..
script:
  - JorG/run_all_tests.sh
