language: python
before_install:
  - sudo apt-get update
  - sudo apt-get upgrade
install:
  - sudo apt-get install python-numpy*
  - sudo apt-get install python-scipy*
  - sudo pip install --user spglib
script:
  - ./run_all_tests.py
