language: python
branches:
  only:
    - experimental
before_install:
  - sudo apt-get update
  - sudo apt-get install -y python3-numpy
  - sudo apt-get install -y python3-scipy
  - sudo apt-get install -y python3-dev
script:
  - ./run_all_tests.sh
