env:
  global:
    - CODACY_PROJECT_TOKEN="020e3d76de3d4467b4997e5d5f20b88a"
branches:
  only:
    - experimental
matrix:
  include:
    language:
      - python
      - cpp
    python:
      - "3.5"
      - "3.6"
      - "3.7"
    install:
      - find ./ -name coverage.sh
      - pip install -r requirements.txt
      - pip install -r requirements_tests.txt	
      - wget ftp://ftp.gnu.org/gnu/gsl/gsl-2.6.tar.gz
      - tar -zxvf gsl-2.6.tar.gz
      - cd gsl-2.6
      - mkdir ${HOME}/gsl
      - ./configure --prefix=${HOME}/gsl
      - make -j2
      - make check
      - make install
    script:
      - ./run_all_tests.sh
      - ./coverage.sh
