language: 
  - python
branches:
  only:
    - experimental
before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y -q python3-numpy python3-scipy python3-dev
  - ls /usr/bin/ | grep g++ 
  - wget ftp://ftp.gnu.org/gnu/gsl/gsl-2.5.tar.gz
  - tar xzf gsl-2.5.tar.gz
  - cd gsl-2.5
  - ./configure
  - make -j8
  - sudo make install
  - cd ..
script:
  - JorG/run_all_tests.sh
