language: python
branches:
  only:
    - experimental
before_install:
  - sudo apt-get update
  - sudo apt-get install -y python3-numpy
  - sudo apt-get install -y python3-scipy
  - sudo apt-get install -y python3-dev
  - wget ftp://ftp.gnu.org/gnu/gsl/gsl-2.5.tar.gz
  - tar xvzf gsl-2.5.tar.gz
  - cd gsl-2.5
  - ./configure
  - CC=g++-8.3 make -j8
  - sudo make install
  - cd ..
script:
  - JorG/run_all_tests.sh
